// Generated by CoffeeScript 1.8.0
(function() {
  describe("Index", function() {
    beforeEach(function() {});
    it("should have some tests in here! - This test should fail to see if everything is working", function() {
      return expect(true).toBeFalsy();
    });
    return it("should initialize the App", function() {
      var newApp;
      newApp = app.initialize;
      return expect(newApp).toBeTruthy();
    });
  });

}).call(this);
